const { chromium } = require('playwright');
const { spawn } = require('child_process');
const SP = process.argv[2], scheme = process.argv[3] || 'dark';
(async () => {
  const srv = spawn('python3', ['-m', 'http.server', '8779', '--bind', '127.0.0.1'], { cwd: process.cwd(), stdio: 'ignore' });
  await new Promise(r => setTimeout(r, 700));
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1.5, serviceWorkers: 'block', colorScheme: scheme });
  await ctx.clock.setFixedTime(new Date('2026-10-08T09:00:00-03:00'));
  await ctx.route(/fonts\.(googleapis|gstatic)\.com/, r => r.abort());
  await ctx.route('**/src/config.js', r => r.fulfill({ status: 200, contentType: 'text/javascript', body: "export const FIREBASE = { apiKey: '' };" }));
  await ctx.route('**/data/prototipo.json', r => r.fulfill({ status: 200, contentType: 'application/json', body: require('fs').readFileSync('tests/fixtures/prototipo.json') }));
  const p = await ctx.newPage();
  p.on('pageerror', e => console.log('PAGEERROR', e.message));
  await p.goto('http://127.0.0.1:8779/');
  await p.fill('#g-code', 'manancial'); await p.fill('#g-name', 'Gustavo Teste'); await p.click('[data-act="g-join"]');
  await p.waitForSelector('#app:not([hidden])'); await p.waitForTimeout(3600);
  const sh = async n => p.screenshot({ path: `${SP}/${scheme}-${n}.png` });
  await p.click('#me-btn'); await p.waitForTimeout(200); await sh('1-menu-membro');
  await p.keyboard.press('Escape'); await p.waitForTimeout(150);
  await p.click('.lcard.next'); await p.waitForTimeout(400); await sh('2-culto');
  await p.locator('.panel [data-act="mv-group"][data-d="1"]').first().click(); await p.waitForTimeout(400); await sh('3-culto-movido');
  await p.locator('.panel [data-act="open-item"]').first().click(); await p.waitForTimeout(500);
  await p.locator('.panel .kchip', { hasText: /^G$/ }).last().click(); await p.waitForTimeout(400); await sh('4-louvor-tom');
  await p.locator('.panel [data-act="close"]').last().click(); await p.waitForTimeout(300);
  await p.locator('.panel [data-act="edit-list"]').first().click(); await p.waitForTimeout(400);
  await p.locator('.kinds').scrollIntoViewIfNeeded(); await sh('5-editor');
  await p.locator('[data-el="items"]').scrollIntoViewIfNeeded(); await sh('6-editor-itens');
  await p.locator('.panel [data-act="close"]').last().click(); await p.waitForTimeout(300);
  await p.locator('.panel [data-act="close"]').last().click(); await p.waitForTimeout(300);
  await p.evaluate(() => localStorage.setItem('lm-demo-adminpass', 'louvor2026'));
  await p.click('#me-btn'); await p.click('[data-act="become-admin"]'); await p.fill('#ba-pass', 'errada'); await p.click('[data-act="become-admin-go"]'); await p.waitForTimeout(300); await sh('7-senha-errada');
  await p.fill('#ba-pass', 'Louvor2026'); await p.click('[data-act="become-admin-go"]'); await p.waitForTimeout(300);
  await p.click('#me-btn'); await p.waitForTimeout(200); await sh('8-menu-admin');
  await p.click('[data-act="admin-pass"]'); await p.waitForTimeout(300); await sh('9-senha');
  await p.keyboard.press('Escape'); await p.waitForTimeout(200);
  await p.click('#me-btn'); await p.click('[data-act="history"]'); await p.waitForTimeout(3000); await sh('10-historico');
  await b.close(); srv.kill();
})();
